# Generated by Django 5.0.6 on 2026-03-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0007_rename_is_add_userpermissions_is_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
