# Generated by Django 5.0.6 on 2026-03-08 17:04

import UserServices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0008_alter_users_profile_pic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', UserServices.models.UsersManager()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Staff', 'Staff')], default='Admin', max_length=50, null=True),
        ),
    ]
