# Generated by hand (mirrors `makemigrations analytics`) on 2026-09-30.
# TrackedEvent has no FKs, so this migration needs no dependencies.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('ga4', 'Google Analytics 4'), ('gtm', 'Google Tag Manager'), ('meta_pixel', 'Meta Pixel'), ('adsense', 'Google AdSense'), ('internal', 'Internal event log')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='TrackedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='analytics_tr_event_0e1b6a_idx')],
            },
        ),
    ]
