# Generated by Django 5.0.6 on 2026-10-04 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trackedevent',
            new_name='analytics_t_event_09b504_idx',
            old_name='analytics_tr_event_0e1b6a_idx',
        ),
    ]
