# Generated by Django 5.0.6 on 2026-07-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodorder_foodorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
