# Generated by Django 5.0.6 on 2026-07-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_foodorder_delivery_lat_foodorder_delivery_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
