# Generated by Django 5.0.6 on 2026-07-21 18:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_rider_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('food_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('restaurant_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rider_base_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rider_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('platform_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rider_name', models.CharField(blank=True, default='', max_length=120)),
                ('customer_payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('NA', 'Not applicable')], default='PENDING', max_length=8)),
                ('rider_cash_status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('NA', 'Not applicable')], default='PENDING', max_length=8)),
                ('rider_payout_status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('NA', 'Not applicable')], default='PENDING', max_length=8)),
                ('restaurant_payout_status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('NA', 'Not applicable')], default='PENDING', max_length=8)),
                ('customer_payment_at', models.DateTimeField(blank=True, null=True)),
                ('rider_cash_at', models.DateTimeField(blank=True, null=True)),
                ('rider_payout_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant_payout_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='food.foodorder')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='food.rider')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_payment_status'], name='food_orders_custome_d96337_idx'), models.Index(fields=['rider_payout_status'], name='food_orders_rider_p_0a4e10_idx'), models.Index(fields=['restaurant_payout_status'], name='food_orders_restaur_0a0b4c_idx')],
            },
        ),
    ]
