# Generated by Django 5.0.6 on 2026-07-22 21:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_ordersettlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=10)),
                ('free_km', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('per_km_fee', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=10)),
                ('min_fee', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=10)),
                ('max_fee', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10)),
                ('rider_base_pay', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10)),
                ('rider_per_km', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=10)),
                ('platform_min_margin', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('round_to_nearest', models.PositiveIntegerField(default=5)),
                ('max_delivery_km', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('rider_cash_ceiling', models.DecimalField(decimal_places=2, default=Decimal('3000.00'), max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Delivery pricing',
            },
        ),
        migrations.AddField(
            model_name='foodorder',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='rider_base_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ordersettlement',
            name='commission_floor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='village',
            name='center_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='center_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5),
        ),
    ]
