# Generated by Django 5.0.6 on 2026-07-24 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_deliveryoffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expo_token', models.CharField(max_length=255, unique=True)),
                ('app', models.CharField(choices=[('customer', 'Customer'), ('rider', 'Rider'), ('restaurant', 'Restaurant')], max_length=12)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=8)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'enabled'], name='food_device_user_id_eb52b9_idx')],
            },
        ),
    ]
