# Generated by Django 5.0.6 on 2026-07-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='is_sharing_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='nav_display_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
