# Generated by Django 5.0.6 on 2026-07-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_rider_is_sharing_location_rider_nav_display_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='is_sharing_location',
            field=models.BooleanField(default=True),
        ),
    ]
