# Generated by Django 5.0.6 on 2026-07-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='source_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
