# Generated by Django 5.0.6 on 2026-07-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_products_price_synced_at_products_source_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='base_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
