# Generated by Django 5.0.6 on 2026-07-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_products_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Per-product shipping fee. Leave blank to use the store's flat rate; 0 means this product ships free.", max_digits=8, null=True),
        ),
    ]
