# Generated by Django 5.0.6 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_products_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='free_shipping',
            field=models.BooleanField(default=False, help_text='Mark this product as an explicit free-shipping promo item.'),
        ),
    ]
