# Generated by Django 5.0.6 on 2026-07-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_products_free_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size_chart',
            field=models.JSONField(blank=True, default=dict, help_text='Size measurements in inches, e.g. {"S":{"chest":36,"length":27},"M":{"chest":38,"length":28}}. Keys beyond chest/length (e.g. "sleeve") are fine -- the storefront renders whatever measurement keys are present, see catalog.scrape_parsers._extract_fabrilife_size_chart.'),
        ),
    ]
