# Generated by Django 5.0.6 on 2026-07-30 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_products_size_chart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name, e.g. Potakait.com', max_length=255)),
                ('slug', models.SlugField(help_text='Stable key used in the API/URLs, e.g. potakait', max_length=64, unique=True)),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('adapter_key', models.CharField(blank=True, choices=[('opencart', 'OpenCart (potakait/canvasit)'), ('fabrilife', 'Fabrilife (Algolia)'), ('', 'No adapter yet')], default='', help_text='Which parser handles this source. Blank means no adapter exists yet -- such a source must stay disabled.', max_length=32)),
                ('supports_search', models.BooleanField(default=False, help_text='Whether this source has a reachable free-text search endpoint (distinct from category browsing, which every enabled source supports).')),
                ('is_enabled', models.BooleanField(default=False, help_text='A disabled source is rejected by the import API with a clear message, not silently skipped.')),
                ('sets_source_url', models.BooleanField(default=False, help_text='Set Products.source_url on import from this source (partner stores only -- this is what the price-sync job re-prices).')),
                ('notes', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('found_count', models.IntegerField(default=0, help_text='How many source_urls were requested for this run.')),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, default='', help_text='Set when the whole run failed outright (e.g. a listing fetch error), not for individual per-item failures -- those are already counted in failed_count.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_import_runs', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='catalog.importsource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportSourceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_path', models.CharField(help_text="Path/slug on the source site, e.g. 'laptops'", max_length=255)),
                ('label', models.CharField(blank=True, default='', help_text="Display label, e.g. 'Laptops'", max_length=255)),
                ('our_category_slug', models.SlugField(help_text="Target taxonomy slug, e.g. 'computers-laptops'", max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.importsource')),
            ],
            options={
                'ordering': ['source_id', 'display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='importsourcecategory',
            constraint=models.UniqueConstraint(fields=('source', 'source_path'), name='uq_import_source_category_path'),
        ),
    ]
