# Generated by Django 5.0.6 on 2026-07-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seed_rokomari_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsource',
            name='adapter_key',
            field=models.CharField(blank=True, choices=[('opencart', 'OpenCart (potakait/canvasit)'), ('fabrilife', 'Fabrilife (Algolia)'), ('rokomari', 'Rokomari.com'), ('', 'No adapter yet')], default='', help_text='Which parser handles this source. Blank means no adapter exists yet -- such a source must stay disabled.', max_length=32),
        ),
    ]
