# Generated by Django 5.0.6 on 2026-07-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_importsource_adapter_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('OTHER', 'Other')], default='', help_text='Tablet, capsule, syrup, injection, cream, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='generic_name',
            field=models.CharField(blank=True, default='', help_text='Active ingredient, e.g. Paracetamol -- the primary search axis for medicines.', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturer',
            field=models.CharField(blank=True, default='', help_text='Pharma company, e.g. Square Pharmaceuticals', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='pack_size',
            field=models.CharField(blank=True, default='', help_text='e.g. "10 x 10", "100 ml"', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='requires_prescription',
            field=models.BooleanField(default=False, help_text='Requires a prescription to purchase -- blocks checkout while StoreConfiguration.rx_sales_enabled is False.'),
        ),
        migrations.AddField(
            model_name='products',
            name='strength',
            field=models.CharField(blank=True, default='', help_text='e.g. "500 mg"', max_length=100),
        ),
    ]
