# Generated by Django 5.0.6 on 2026-08-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_enable_arogga_import_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsource',
            name='adapter_key',
            field=models.CharField(blank=True, choices=[('opencart', 'OpenCart (potakait/canvasit)'), ('fabrilife', 'Fabrilife (Algolia)'), ('rokomari', 'Rokomari.com'), ('arogga', 'Arogga.com (schema.org JSON-LD)'), ('', 'No adapter yet')], default='', help_text='Which parser handles this source. Blank means no adapter exists yet -- such a source must stay disabled.', max_length=32),
        ),
    ]
