# Generated by Django 5.0.6 on 2026-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='module',
            field=models.CharField(choices=[('shop', 'Fabrything Shop'), ('food', 'Fabrything Food'), ('news', 'NobleSeek News'), ('shared', 'Shared (all modules)')], db_index=True, default='shared', max_length=16),
        ),
    ]
