# Generated by Django 5.0.6 on 2026-03-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderService', '0006_remove_purchaseorder_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderinwardedlog',
            name='returned_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='total_amount',
        ),
    ]
