# Generated by Django 5.0.6 on 2026-10-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobleseek', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='nobleseek_a_status_3d46ba_idx',
            old_name='nobleseek_ar_status_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='nobleseek_a_categor_eeda62_idx',
            old_name='nobleseek_ar_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='trendkeyword',
            new_name='nobleseek_t_status_ce5e0a_idx',
            old_name='nobleseek_tr_status_idx',
        ),
        migrations.AlterField(
            model_name='adconfig',
            name='adsense_client',
            field=models.CharField(blank=True, default='', help_text='ca-pub-XXXXXXXXXXXXXXXX', max_length=64),
        ),
        migrations.AlterField(
            model_name='adconfig',
            name='shop_ads_enabled',
            field=models.BooleanField(default=False, help_text='Keep OFF to minimize shop ads'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, default='', help_text='1-2 lines shown on cards + meta description fallback', max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='fb_post_url',
            field=models.URLField(blank=True, default='', help_text='Link back to NobleSeek FB post for traffic proof', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["cricket","bangladesh"]'),
        ),
        migrations.AlterField(
            model_name='trendkeyword',
            name='geo',
            field=models.CharField(default='BD', help_text='BD or US (trends region)', max_length=8),
        ),
        migrations.AlterField(
            model_name='trendkeyword',
            name='traffic_label',
            field=models.CharField(blank=True, default='', help_text='e.g. 200K+ searches', max_length=60),
        ),
        migrations.AlterField(
            model_name='trendkeyword',
            name='traffic_score',
            field=models.IntegerField(default=0, help_text='Relative interest 0-100 or search volume'),
        ),
    ]
