# Generated by Django 5.0.6 on 2026-04-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0005_alter_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list, help_text='List of available sizes, e.g. ["S","M","L","XL"]'),
        ),
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(blank=True, default='', help_text='e.g. Cotton, Polyester, Silk', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='size_chart',
            field=models.JSONField(blank=True, default=dict, help_text='Size measurements in inches, e.g. {"S":{"chest":36,"length":27},"M":{"chest":38,"length":28}}'),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='addition_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='dimensions',
            field=models.CharField(blank=True, default='0x0x0', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='products',
            name='html_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='products',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='seo_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='products',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='products',
            name='tax_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='uom',
            field=models.CharField(blank=True, default='PCS', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
