# Generated by Django 5.0.6 on 2026-07-15 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_id_inventory', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item_id_inventory', to='purchasing.purchaseorderitems'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_item_inwarded_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item_inwarded_item_id_inventory', to='purchasing.purchaseorderiteminwardedlog'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_inventory_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_inventory_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='inventory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_id_inventory_log', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='po_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_id_inventory_log', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='so_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_id_inventory_log', to='purchasing.salesorder'),
        ),
        migrations.AddField(
            model_name='rackandshelvesandfloor',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_rack_shelf_floor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rackandshelvesandfloor',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_rack_shelf_floor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='rack_shelf_floor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_shelf_floor_id_inventory_log', to='inventory.rackandshelvesandfloor'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rack_shelf_floor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_shelf_floor_id_inventory', to='inventory.rackandshelvesandfloor'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_warhouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_warhouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_manager_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rackandshelvesandfloor',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_id_rack_shelf_floor', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_id_inventory_log', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_id_inventory', to='inventory.warehouse'),
        ),
    ]
