# Generated by Django 5.0.6 on 2026-07-15 22:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_shipping_rate', models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Flat shipping charge applied to every order.', max_digits=8)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: orders with subtotal >= this ship free. Leave blank to always charge the fixed rate.', max_digits=10, null=True)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('store_name', models.CharField(default='Fabrything', max_length=120)),
                ('support_phone', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configuration',
            },
        ),
    ]
