# Generated by Django 5.0.6 on 2026-07-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imageblob'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='whatsapp_admin_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='WhatsAppAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=32)),
                ('related_order', models.CharField(blank=True, default='', max_length=32)),
                ('payload_summary', models.CharField(blank=True, default='', max_length=300)),
                ('success', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'related_order'], name='core_whatsa_kind_4450e7_idx')],
            },
        ),
    ]
