# Generated by Django 5.0.6 on 2026-07-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storeconfiguration_whatsapp_admin_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='messenger_page_id',
            field=models.CharField(blank=True, default='', help_text='Facebook Page ID (numeric) or Page username — either works in an m.me/ link. Leave blank to hide the Messenger button on the storefront.', max_length=100),
        ),
    ]
