# Generated by Django 5.0.6 on 2026-07-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_set_messenger_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='whatsapp_chat_number',
            field=models.CharField(blank=True, default='', help_text="WhatsApp number for the floating chat button (digits only, no '+', e.g. 8801842168117 -- used as wa.me/<this value>). Leave blank to hide the button on the storefront and food frontend.", max_length=20),
        ),
    ]
