# Generated by Django 5.0.6 on 2026-07-29 09:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_set_whatsapp_chat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='markup_floor',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Minimum taka markup applied to every product regardless of price, so a cheap item still carries a guaranteed minimum margin.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text="Percentage markup applied to a product's base_price. Clamped to 0-100 on save -- a mis-typed 500% would otherwise 6x every price.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
