# Generated by Django 5.0.6 on 2026-07-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_storeconfiguration_markup_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='rx_sales_enabled',
            field=models.BooleanField(default=False, help_text='Allow checkout of prescription-required medicines. Leave off until a DGDA licence is in hand -- every requires_prescription product is blocked at checkout while this is False, regardless of any other setting.'),
        ),
    ]
