# Generated by Django 5.0.6 on 2026-08-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_storeconfiguration_rx_sales_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='alert_email',
            field=models.EmailField(blank=True, default='fabrything@gmail.com', help_text='Mailbox that receives a notification for every new order. Leave blank to disable email alerts.', max_length=254),
        ),
    ]
