# Generated by Django 5.0.6 on 2026-08-06 05:45

from django.db import migrations, models

SUPPORT_PHONE = '8801842168117'


def set_support_phone_if_blank(apps, schema_editor):
    """Put the owner's number on the existing singleton row.

    Changing the field default only affects rows created afterwards, and
    production's StoreConfiguration row already exists with support_phone=''
    — so without this the live storefront would keep showing no phone number
    at all. Only ever fills a BLANK value: if the owner has since set a
    different number from the admin panel, this must not overwrite it.
    """
    StoreConfiguration = apps.get_model('core', 'StoreConfiguration')
    StoreConfiguration.objects.filter(support_phone='').update(support_phone=SUPPORT_PHONE)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_storeconfiguration_alert_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconfiguration',
            name='support_phone',
            field=models.CharField(blank=True, default=SUPPORT_PHONE, max_length=20),
        ),
        # Reverse is a no-op: blanking the number again on a rollback would be
        # a worse outcome than leaving it set, and it is admin-editable anyway.
        migrations.RunPython(set_support_phone_if_blank, migrations.RunPython.noop),
    ]
