# Generated by Django 5.0.6 on 2026-07-29 14:52

import django.db.models.deletion
import printing.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_alter_products_size_chart'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_tiers', models.JSONField(blank=True, default=printing.models.default_quantity_tiers, help_text='List of {"min_qty": int, "discount_percent": number}, ascending by min_qty. The highest tier at or below the order quantity applies.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintablePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('available_colors', models.JSONField(blank=True, default=list)),
                ('available_sizes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printable_preset', to='catalog.products')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('FREE', 'Free Size')], default='', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('brief', models.TextField()),
                ('reference_images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_DESIGN', 'In Design'), ('PROOF_READY', 'Proof Ready'), ('REVISION_REQUESTED', 'Revision Requested'), ('APPROVED', 'Approved'), ('IN_PRODUCTION', 'In Production'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20)),
                ('quoted_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quoted_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agreed_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agreed_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('staff_notes', models.TextField(blank=True, default='')),
                ('chat_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_request', to='chat.chatthread')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_requests', to=settings.AUTH_USER_MODEL)),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_requests', to='printing.printablepreset')),
                ('print_areas', models.ManyToManyField(blank=True, related_name='print_requests', to='printing.printarea')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_requests', to='catalog.products')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(max_length=500)),
                ('version', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REVISION_REQUESTED', 'Revision Requested')], default='PENDING', max_length=20)),
                ('customer_feedback', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('print_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='printing.printrequest')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PrintRosterLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_name', models.CharField(max_length=120)),
                ('number', models.CharField(blank=True, default='', max_length=10)),
                ('size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('FREE', 'Free Size')], default='', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('print_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_lines', to='printing.printrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='printrequest',
            index=models.Index(fields=['status', '-created_at'], name='print_req_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='printrequest',
            index=models.Index(fields=['customer', '-created_at'], name='print_req_customer_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='printproof',
            constraint=models.UniqueConstraint(fields=('print_request', 'version'), name='unique_proof_version_per_request'),
        ),
    ]
