# Generated by Django 5.0.6 on 2026-08-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_seed_printable_presets'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('apparel', 'Apparel'), ('headwear-bags', 'Headwear & bags'), ('drinkware', 'Drinkware'), ('office', 'Office & stationery'), ('accessories-tech', 'Accessories & tech')], default='apparel', max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=160)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
