# Generated by Django 5.0.6 on 2026-07-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_products_size_chart'),
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(help_text='Transparent PNG product cut-out. Upload via POST /api/uploads/ and store the returned URL here.', max_length=500)),
                ('eyebrow', models.CharField(blank=True, default='', max_length=60)),
                ('headline', models.CharField(max_length=200)),
                ('subtext', models.CharField(blank=True, default='', max_length=300)),
                ('animation_style', models.CharField(choices=[('FADE_UP', 'Fade up'), ('SLIDE_IN', 'Slide in'), ('FLOAT', 'Float / parallax'), ('ZOOM', 'Zoom')], default='FADE_UP', max_length=20)),
                ('background', models.CharField(default='#1a1a2e', help_text="CSS colour or gradient for the banner background, e.g. '#1a1a2e' or 'linear-gradient(135deg,#1a1a2e,#16213e)'.", max_length=255)),
                ('cta_label', models.CharField(blank=True, default='Shop Now', max_length=60)),
                ('cta_url', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cta_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.products')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
