# Generated by Django 5.0.6 on 2026-07-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_products_dosage_form_products_generic_name_and_more'),
        ('storefront', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(default='https://www.rokomari.com/', max_length=300)),
                ('affiliate_id', models.CharField(default='Ma8A710222i0iRo', help_text="Rokomari's 'affId' query param -- the owner's affiliate account id.", max_length=64)),
                ('sub_id', models.CharField(default='70278', help_text="Rokomari's 'affs' query param (sub-affiliate/site id).", max_length=32)),
                ('cookie_window_seconds', models.PositiveIntegerField(default=604800, help_text="Rokomari's 'cma' query param -- attribution cookie lifetime in seconds (604800 = 7 days).")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Affiliate Config',
                'verbose_name_plural': 'Affiliate Config',
            },
        ),
        migrations.CreateModel(
            name='AffiliateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('rokomari', 'Rokomari.com')], default='rokomari', max_length=32)),
                ('remote_product_id', models.CharField(help_text="The product's id on the affiliate site (Rokomari's numeric productId).", max_length=64)),
                ('source_url', models.URLField(help_text="The affiliate site's own product page (reference only -- no tracking params).", max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Commission earned per sale, when the programme discloses it.', max_digits=10, null=True)),
                ('link_type', models.CharField(choices=[('CART', 'Cart link (quick-cart)'), ('PRODUCT', 'Product page link')], default='CART', help_text='Cart (quick-buy) link or product-page link -- chosen per product.', max_length=10)),
                ('manual_short_link', models.URLField(blank=True, default='', help_text="Optional pasted rkmri.co short link. When set, this is used INSTEAD of the constructed link -- the owner's escape hatch if the constructed-link scheme ever stops attributing.", max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('show_in_sidebar', models.BooleanField(default=False, help_text='Rotating sidebar/section widget.')),
                ('show_on_deals_page', models.BooleanField(default=False, help_text='Dedicated Deals page.')),
                ('show_in_category_grid', models.BooleanField(default=False, help_text='Inject into the category-grid pages listed in grid_categories.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grid_categories', models.ManyToManyField(blank=True, help_text="Which of our taxonomy categories this product's grid injection appears in.", related_name='affiliate_products', to='catalog.categories')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
