# Generated by Django 5.0.6 on 2026-08-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_affiliateconfig_affiliateproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='layout',
            field=models.CharField(choices=[('PRODUCT', 'Product cut-out beside text'), ('FULL_BLEED', 'Full-width image')], default='PRODUCT', help_text='PRODUCT composites a transparent cut-out beside the text and animates it; FULL_BLEED fills the hero with a wide image.', max_length=20),
        ),
        migrations.AlterField(
            model_name='banner',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
